# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac82f6c4e9ac04e28729ab76e80a5b2b20401915630804924c38ac0279bfd501a87d30d5ad1133a91fad33a8e8ab9d733cf67434b30ad8e156a0b5833c48393e

test:
  secret_key_base: 8488412b99897c6f777e1999bce960d73253b1d01968a656cd79be860d4740f0a222a308f1868fe058f927bb65db3b31d5cd2a09aab3556fd37fc8d714bb0650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
